
export interface JournalEntry {
  id: string;
  doing: string;
  feeling: string;
  timestamp: number;
}

export interface MindfulnessExercise {
  id: string;
  title: string;
  durationMinutes: number; // 1 to 5
  focus: ExerciseFocus;
  instructions: string; // Generated by AI
}

export enum ExerciseFocus {
  BREATH = "Respiración",
  SOUNDS = "Sonidos del Entorno",
  SENSATIONS = "Sensaciones Físicas",
  // IMAGE_GENERATION = "Generación de Imagen", // Removed
}

export interface MindfulnessChallenge {
  id: string;
  description: string; // Generated by AI
  date: string; // YYYY-MM-DD
  isCompleted: boolean;
}

// PresenceCheckinPrompt interface removed

export interface FocusGame {
  id: string;
  name: string;
  description: string;
}